
- name: Bootstrap director
  hosts: all
  gather_facts: False
  any_errors_fatal: true
  become: true
  vars:
    director_development_env: true
  tasks:
    - name: Execute development script
      script: "{{ playbook_dir }}/dev-setup.sh"
      when:
        - director_development_env | bool

- name: Start director server
  hosts: director_server
  gather_facts: False
  any_errors_fatal: true
  become: true
  vars:
    director_development_env: true
  tasks:
    - name: Generate curve keys
      command: "{{ director_development_env | bool | ternary('/opt/director/bin', '/usr/bin') }}/director manage --generate-keys"
    - name: Specifying a destination path
      fetch:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        flat: yes
      loop:
        - /etc/director/private_keys/client.key_secret
        - /etc/director/public_keys/client.key
        - /etc/director/public_keys/server.key
    - name: Development server block
      block:
      - name: Setup director server service unit
        command: /opt/director/bin/director-server-systemd
      - name: Load director server service unit
        systemd:
          state: restarted
          daemon_reload: yes
          name: director-server.service
      when:
        - director_development_env | bool

- name: Start director clients
  hosts: director_clients
  gather_facts: False
  any_errors_fatal: true
  become: true
  vars:
    director_development_env: true
  tasks:
    - name: Ensure key directories exists
      file:
        path: "{{ item }}"
        state: director
      loop:
        - /etc/director
        - /etc/director/private_keys
        - /etc/director/public_keys
    - name: Specifying a destination path
      copy:
        src: "/tmp/client.key_secret"
        dest: "/etc/director/private_keys/client.key_secret"
    - name: Specifying a destination path
      copy:
        src: "{{ item }}"
        dest: "/etc/director/public_keys/{{ item | basename }}"
      loop:
        - /tmp/client.key
        - /tmp/server.key
    - name: Development client block
      block:
      - name: Setup director client service unit
        command: /opt/director/bin/director-client-systemd
      - name: Load director client service unit
        systemd:
          state: restarted
          daemon_reload: yes
          name: director-client.service
      when:
        - director_development_env | bool
