theme: jekyll-theme-dinky
title: Director
description: >-
  An asynchronous deployment and operations platform with the aim to
  better enable simplicity, faster time to delivery, and consistency.
markdown: kramdown
