theme: jekyll-theme-dinky
title: Directord
description: >-
  An asynchronous deployment and operations platform with the aim to
  better enable simplicity, faster time to delivery, and consistency.
markdown: kramdown
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
