name: Run container build test
on: [pull_request]
jobs:
  container_build_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build new directord container
      run: docker build -t directord -f Containerfile .
