name: Run pull-request facter workflows
on:
  pull_request:
    paths:
      - '.github/workflows/pull-request-facter.yml'
      - 'components/facter.py'
      - 'orchestrations/functional-tests-facter.yaml'

jobs:
  functional_facter_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run install
        run: sudo bash tools/dev-setup.sh /opt/directord python3 ${{ github.workspace }}
      - name: Run server service install
        run: |
          sudo /opt/directord/bin/directord-server-systemd
          sudo systemctl daemon-reload
          sudo systemctl restart directord-server
      - name: Run client service install
        run: |
          sudo /opt/directord/bin/directord-client-systemd
          sudo systemctl daemon-reload
          sudo systemctl restart directord-client
      - name: Wait for client online
        run: |
          timeout 120 bash -c 'while ! sudo /opt/directord/bin/directord manage --list-nodes; do sleep 1; done'
      - name: Build current container and run client
        run: |
          sudo apt-get install -y facter

      - name: Wait for client online
        run: |
          timeout 120 bash -c 'while ! sudo /opt/directord/bin/directord manage --list-nodes; do sleep 1; done'
      - name: Execute functional check
        run: |
          cd /opt/directord/share/directord/orchestrations
          sudo timeout 240 /opt/directord/bin/directord \
                                              orchestrate \
                                              functional-tests-facter.yaml \
                                              --poll \
                                              --check
      - name: Generate log details
        run: |
          sudo journalctl -u directord-client -n 2000 &> /tmp/directord-client.log || true
          sudo journalctl -u directord-server -n 2000 &> /tmp/directord-server.log || true
          sudo /opt/directord/bin/directord manage --list-nodes &> /tmp/directord-nodes.log || true
          sudo /opt/directord/bin/directord manage --dump-cache &> /tmp/directord-cache.log || true
          sudo /opt/directord/bin/directord manage --export-jobs /tmp/directord-jobs-export.log || true
          sudo cp -R /etc/directord /tmp/
          sudo find /tmp/directord -type d -exec chmod 0755 {} \;
          sudo find /tmp/directord -type f -exec chmod 0644 {} \;
        if: failure()
      - name: Upload build Log artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: functional-test-logs
          path: /tmp/directord*
