
name: Directord release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Build the python package
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade twine build wheel setuptools
        python3 -m build --no-isolation
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/directord*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
