name: Test RPM workflows
on:
- push
- pull_request
jobs:
  build_test_rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Create source tarball
      run: |
        name=${PWD##*/}
        cd ..
        tar -czf /tmp/directord.tar.gz "${name}"
        mv /tmp/directord.tar.gz ${{ github.workspace }}/contrib/container-build/
    - name: Build builder container image
      run: docker build -t directord-builder -f ./contrib/container-build/Containerfile ./contrib/container-build
    - name: Run builder container
      run: |
        export RELEASE_VERSION=$(awk -F'"' '/version/ {print $2}' ${{ github.workspace }}/directord/meta.py)
        docker run --env RELEASE_VERSION="${RELEASE_VERSION}" --net=host -v ${{ github.workspace }}/contrib:/home/builder/rpm directord-builder
    - name: Upload build Log artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs-el8
        path: contrib/build/*.log
    - uses: actions/upload-artifact@v2
      with:
        name: Upload RPM artifact
        path: |
          contrib/build/*.rpm
